/* ============================================================================
   FERRO FRAGOSO — Base de datos de plantillas de contratos (México)
   ----------------------------------------------------------------------------
   Cada contrato se compone de "bloques". Tipos de bloque:
     h   = título de cláusula (encabezado)
     p   = párrafo de cuerpo (justificado)
     i   = inciso / declaración con sangría
     note= nota / cláusula opcional destacada
     sub = subtítulo centrado (para documentos de varias partes)
     sign= bloque de firmas [ [col izq...], [col der...] ]
     fn  = nota al pie (fundamento legal) — se numera automáticamente
     br  = salto de página
   Los campos editables se escriben entre dobles llaves: {{Etiqueta del campo}}
   Las etiquetas iguales se rellenan una sola vez en el formulario.
   [CLÁUSULA OPCIONAL] al inicio de un párrafo lo marca como opcional.
   ============================================================================ */

const CONTRATOS = [
  /* 01 ---------------------------------------------------------------- */
  {
    id: "01_prestacion_servicios",
    que_es: "Es un acuerdo en el que un profesional independiente se compromete a realizar un servicio específico a favor del cliente a cambio de una retribución.",
    para_que_sirve: "Para formalizar la relación entre un freelancer, consultor o agencia y su cliente, estableciendo entregables, honorarios y plazos claros sin crear una relación laboral.",
    alcance_legal: "Protege la propiedad intelectual, delimita la responsabilidad del prestador y asegura el pago. Deja claro que no hay subordinación laboral, previniendo demandas laborales.",
    titulo: "Contrato de prestación de servicios profesionales",
    categoria: "Demanda general",
    base: "Arts. 2606 a 2615 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Contrato de prestación de servicios profesionales que celebran, por una parte, {{Nombre/Razón social del cliente}}, a quien en lo sucesivo se le denominará “EL CLIENTE”; y por la otra, {{Nombre/Razón social del prestador}}, a quien se le denominará “EL PRESTADOR”; y cuando actúen conjuntamente, “LAS PARTES”, al tenor de las siguientes declaraciones y cláusulas.[[1]]" },
      { t: "h", x: "DECLARACIONES" },
      { t: "i", x: "I. Declara EL CLIENTE que es {{Tipo de persona del cliente}}, con RFC {{RFC del cliente}}, y domicilio en {{Domicilio del cliente}}; que tiene interés en contratar los servicios objeto de este contrato." },
      { t: "i", x: "II. Declara EL PRESTADOR que cuenta con la cédula/experiencia número {{Cédula o experiencia del prestador}}, RFC {{RFC del prestador}}, y domicilio en {{Domicilio del prestador}}; y que cuenta con los conocimientos y recursos necesarios." },
      { t: "i", x: "III. Declaran LAS PARTES que se reconocen mutuamente la personalidad con que se ostentan y que es su voluntad obligarse en los términos del presente contrato." },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "EL PRESTADOR se obliga a prestar a favor de EL CLIENTE los siguientes servicios profesionales: {{Descripción de los servicios}}. Los servicios se prestarán con autonomía técnica, sin que exista subordinación de carácter laboral entre LAS PARTES." },
      { t: "h", x: "SEGUNDA. Honorarios y forma de pago" },
      { t: "p", x: "EL CLIENTE pagará a EL PRESTADOR la cantidad de ${{Monto de honorarios}} ({{Monto con letra}} pesos M.N.), más el IVA que corresponda. El pago se realizará de la siguiente forma: {{Forma de pago}}, mediante transferencia a la cuenta {{Datos bancarios}}.[[2]]" },
      { t: "note", x: "EL PRESTADOR entregará el Comprobante Fiscal Digital por Internet (CFDI) correspondiente por cada pago recibido." },
      { t: "h", x: "TERCERA. Vigencia" },
      { t: "p", x: "El presente contrato tendrá una vigencia de {{Plazo de vigencia}}, a partir del {{Fecha de inicio}} y hasta el {{Fecha de término}}. [CLÁUSULA OPCIONAL] Podrá prorrogarse por periodos iguales mediante acuerdo escrito de LAS PARTES." },
      { t: "h", x: "CUARTA. Obligaciones del prestador" },
      { t: "p", x: "EL PRESTADOR se obliga a: (i) prestar los servicios con diligencia, calidad y probidad profesional; (ii) guardar confidencialidad sobre la información de EL CLIENTE; (iii) responder de los daños y perjuicios que cause por negligencia, impericia o dolo, conforme al art. 2615 del Código Civil Federal." },
      { t: "h", x: "QUINTA. Obligaciones del cliente" },
      { t: "p", x: "EL CLIENTE se obliga a: (i) pagar puntualmente los honorarios pactados; (ii) proporcionar la información y elementos necesarios para la prestación de los servicios; (iii) {{Otras obligaciones del cliente}}." },
      { t: "h", x: "SEXTA. Propiedad intelectual" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Los derechos patrimoniales sobre los entregables corresponderán a {{Titular de derechos patrimoniales}} una vez cubierto el pago total. Los derechos morales son irrenunciables e inalienables y corresponden al autor conforme a la Ley Federal del Derecho de Autor." },
      { t: "h", x: "SÉPTIMA. Confidencialidad" },
      { t: "p", x: "LAS PARTES se obligan a mantener estricta confidencialidad respecto de toda información que llegue a su conocimiento con motivo de este contrato, obligación que subsistirá por {{Plazo de confidencialidad}} posteriores a su terminación." },
      { t: "h", x: "OCTAVA. Terminación anticipada" },
      { t: "p", x: "Cualquiera de LAS PARTES podrá dar por terminado el contrato mediante aviso por escrito con {{Días de aviso de terminación}} días naturales de anticipación, cubriendo los servicios efectivamente prestados." },
      { t: "h", x: "NOVENA. Rescisión" },
      { t: "p", x: "Será causa de rescisión el incumplimiento de cualquiera de las obligaciones, previa notificación por escrito y sin que se subsane dentro de los {{Días para subsanar}} días siguientes." },
      { t: "h", x: "DÉCIMA. Jurisdicción y ley aplicable" },
      { t: "p", x: "LAS PARTES se someten a las leyes federales aplicables y a la jurisdicción de los tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído que fue el presente contrato y enteradas LAS PARTES de su contenido y alcance legal, lo firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL CLIENTE", "{{Nombre/Razón social del cliente}}"], b: ["EL PRESTADOR", "{{Nombre/Razón social del prestador}}"] },
    ],
    fns: [
      "La prestación de servicios profesionales se rige por los artículos 2606 a 2615 del Código Civil Federal. El prestador conserva independencia técnica; no existe subordinación laboral.",
      "Conforme al art. 2609 CCF, a falta de convenio sobre la retribución, se fijará atendiendo a la costumbre del lugar, la importancia del trabajo y la reputación profesional.",
    ],
  },

  /* 02 ---------------------------------------------------------------- */
  {
    id: "02_arrendamiento",
    que_es: "Es el contrato mediante el cual el propietario de un inmueble (arrendador) otorga el uso temporal del mismo a otra persona (arrendatario) a cambio de una renta.",
    para_que_sirve: "Para rentar casas, departamentos, oficinas o locales comerciales de forma segura, estableciendo reglas claras sobre el uso, pagos y mantenimiento.",
    alcance_legal: "Garantiza el pago puntual mediante depósito o fiador, y establece las causales de rescisión para poder desalojar legalmente en caso de incumplimiento.",
    titulo: "Contrato de arrendamiento de inmueble",
    categoria: "Demanda general",
    base: "Arts. 2398 a 2496 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Contrato de arrendamiento que celebran, por una parte, {{Nombre del arrendador}}, en lo sucesivo “EL ARRENDADOR”; y por la otra, {{Nombre del arrendatario}}, en lo sucesivo “EL ARRENDATARIO”, conforme a las siguientes declaraciones y cláusulas.[[1]]" },
      { t: "h", x: "DECLARACIONES" },
      { t: "i", x: "I. Declara EL ARRENDADOR ser propietario o tener la legítima posesión del inmueble ubicado en {{Domicilio del inmueble}}, lo que acredita con {{Documento que acredita propiedad}}." },
      { t: "i", x: "II. Declara EL ARRENDATARIO tener interés en arrendar el inmueble para destinarlo a {{Destino del inmueble}}, y contar con capacidad para obligarse." },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "EL ARRENDADOR concede el uso y goce temporal del inmueble descrito, el cual se entrega en buen estado de conservación, según el inventario que se anexa." },
      { t: "h", x: "SEGUNDA. Destino" },
      { t: "p", x: "El inmueble se destinará exclusivamente para {{Destino del inmueble}}. EL ARRENDATARIO no podrá darle un uso distinto sin consentimiento previo y por escrito." },
      { t: "h", x: "TERCERA. Renta" },
      { t: "p", x: "La renta mensual será de ${{Monto de renta mensual}} ({{Renta con letra}} pesos M.N.), pagadera por mensualidades adelantadas dentro de los primeros {{Días para pagar renta}} días de cada mes, mediante transferencia a la cuenta {{Datos bancarios del arrendador}}.[[2]]" },
      { t: "h", x: "CUARTA. Incremento de renta" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] La renta se incrementará anualmente en un {{Porcentaje de incremento}}% o conforme al INPC publicado por el INEGI, lo que resulte mayor." },
      { t: "h", x: "QUINTA. Depósito en garantía" },
      { t: "p", x: "EL ARRENDATARIO entrega la cantidad de ${{Monto del depósito}} por concepto de depósito en garantía, que será devuelta al término del contrato previa verificación del estado del inmueble, sin generar intereses." },
      { t: "h", x: "SEXTA. Vigencia" },
      { t: "p", x: "El contrato tendrá vigencia forzosa de {{Plazo del arrendamiento}}, del {{Fecha de inicio}} al {{Fecha de término}}." },
      { t: "h", x: "SÉPTIMA. Servicios y mantenimiento" },
      { t: "p", x: "Serán por cuenta de EL ARRENDATARIO los servicios de {{Servicios a cargo del arrendatario}}. Las reparaciones estructurales y por vicios ocultos corresponderán a EL ARRENDADOR (art. 2412 CCF)." },
      { t: "h", x: "OCTAVA. Prohibiciones" },
      { t: "p", x: "EL ARRENDATARIO no podrá subarrendar, ceder o traspasar el inmueble, ni realizar modificaciones a la estructura, sin autorización previa y por escrito." },
      { t: "h", x: "NOVENA. Fiador / obligado solidario" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Comparece {{Nombre del fiador}} como obligado solidario, señalando como garantía el inmueble ubicado en {{Domicilio del inmueble en garantía}}." },
      { t: "h", x: "DÉCIMA. Terminación y desocupación" },
      { t: "p", x: "Al término del contrato, EL ARRENDATARIO se obliga a desocupar y entregar el inmueble en las mismas condiciones en que lo recibió, salvo el deterioro por uso normal." },
      { t: "h", x: "DÉCIMA PRIMERA. Rescisión" },
      { t: "p", x: "Serán causas de rescisión: la falta de pago de {{Mensualidades para rescisión}} o más mensualidades; el uso distinto al pactado; el subarriendo no autorizado; y el incumplimiento de cualquier obligación." },
      { t: "h", x: "DÉCIMA SEGUNDA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL ARRENDADOR", "{{Nombre del arrendador}}"], b: ["EL ARRENDATARIO", "{{Nombre del arrendatario}}"] },
    ],
    fns: [
      "El arrendamiento se regula por los arts. 2398 a 2496 del Código Civil Federal (y su equivalente estatal). Verifique disposiciones locales sobre plazos, incrementos y casa-habitación.",
      "Conforme al art. 2448-D CCF, en arrendamiento para habitación la renta solo podrá aumentarse anualmente y hasta el porcentaje que la ley local permita.",
    ],
  },

  /* 03 ---------------------------------------------------------------- */
  {
    id: "03_compraventa",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Contrato de compraventa",
    categoria: "Demanda general",
    base: "Arts. 2248 a 2326 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Contrato de compraventa que celebran, por una parte, {{Nombre del vendedor}}, “EL VENDEDOR”; y por la otra, {{Nombre del comprador}}, “EL COMPRADOR”, al tenor de lo siguiente.[[1]]" },
      { t: "h", x: "DECLARACIONES" },
      { t: "i", x: "I. Declara EL VENDEDOR ser legítimo propietario del bien, libre de todo gravamen, embargo o limitación de dominio, lo que acredita con {{Documento que acredita propiedad}}." },
      { t: "i", x: "II. Declara EL COMPRADOR tener interés y capacidad para adquirir el bien en los términos pactados." },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "EL VENDEDOR transfiere la propiedad a EL COMPRADOR del siguiente bien: {{Descripción del bien}}." },
      { t: "h", x: "SEGUNDA. Precio" },
      { t: "p", x: "El precio total es de ${{Precio total}} ({{Precio con letra}} pesos M.N.), que EL COMPRADOR pagará de la siguiente forma: {{Forma de pago}}." },
      { t: "h", x: "TERCERA. Forma y lugar de pago" },
      { t: "p", x: "El pago se realizará mediante {{Medio de pago}} en {{Lugar de pago}}. EL VENDEDOR extenderá el comprobante correspondiente." },
      { t: "h", x: "CUARTA. Entrega" },
      { t: "p", x: "EL VENDEDOR entregará el bien el día {{Fecha de entrega}} en {{Lugar de entrega}}. A partir de la entrega, los riesgos corren por cuenta de EL COMPRADOR." },
      { t: "h", x: "QUINTA. Reserva de dominio" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] EL VENDEDOR se reserva la propiedad del bien hasta que EL COMPRADOR cubra la totalidad del precio (arts. 2312 a 2315 CCF)." },
      { t: "h", x: "SEXTA. Saneamiento y vicios ocultos" },
      { t: "p", x: "EL VENDEDOR responde por la evicción y por los vicios o defectos ocultos del bien (arts. 2119 a 2162 CCF), salvo pacto expreso en contrario informado a EL COMPRADOR." },
      { t: "h", x: "SÉPTIMA. Gastos e impuestos" },
      { t: "p", x: "Los gastos, impuestos y derechos serán cubiertos por {{Responsable de gastos}}." },
      { t: "h", x: "OCTAVA. Incumplimiento" },
      { t: "p", x: "El incumplimiento facultará a la parte afectada para exigir el cumplimiento forzoso o la rescisión, con el pago de daños y perjuicios." },
      { t: "h", x: "NOVENA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero.[[2]]" },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL VENDEDOR", "{{Nombre del vendedor}}"], b: ["EL COMPRADOR", "{{Nombre del comprador}}"] },
    ],
    fns: [
      "La compraventa se rige por los arts. 2248 a 2326 del CCF. Hay compraventa cuando uno se obliga a transferir la propiedad de una cosa y el otro a pagar un precio cierto y en dinero (art. 2248).",
      "La compraventa de inmuebles de valor alto debe otorgarse en escritura pública ante notario (art. 2320 CCF). Esta plantilla es apta para bienes muebles o como contrato preparatorio.",
    ],
  },

  /* 04 ---------------------------------------------------------------- */
  {
    id: "04_nda",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Contrato de confidencialidad (NDA)",
    categoria: "Demanda general",
    base: "Ley de la Propiedad Industrial (secretos industriales) y art. 1832 CCF",
    bloques: [
      { t: "p", x: "Contrato de confidencialidad que celebran {{Parte reveladora}}, “LA PARTE REVELADORA”; y {{Parte receptora}}, “LA PARTE RECEPTORA”.[[1]]" },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "Establecer los términos bajo los cuales LAS PARTES protegerán la información confidencial que se compartan con motivo de {{Propósito del NDA}}." },
      { t: "h", x: "SEGUNDA. Información confidencial" },
      { t: "p", x: "Se considera “Información Confidencial” toda información técnica, comercial, financiera, estratégica, de clientes, know-how, secretos industriales, código, diseños y cualquier dato marcado como confidencial o que por su naturaleza deba considerarse como tal." },
      { t: "h", x: "TERCERA. Exclusiones" },
      { t: "p", x: "No se considera confidencial la información que: (i) sea de dominio público sin culpa de la receptora; (ii) ya estuviera legítimamente en su poder; (iii) sea desarrollada de forma independiente; o (iv) deba revelarse por mandato de autoridad." },
      { t: "h", x: "CUARTA. Obligaciones de la parte receptora" },
      { t: "p", x: "LA PARTE RECEPTORA se obliga a: (i) usar la información únicamente para el propósito pactado; (ii) no divulgarla a terceros sin autorización previa y por escrito; (iii) resguardarla con diligencia; y (iv) limitar el acceso a quienes necesiten conocerla." },
      { t: "h", x: "QUINTA. Vigencia y subsistencia" },
      { t: "p", x: "El contrato estará vigente durante {{Vigencia de la relación}}. La obligación de confidencialidad subsistirá por {{Años de subsistencia}} años posteriores a su terminación." },
      { t: "h", x: "SEXTA. Devolución de información" },
      { t: "p", x: "Al terminar el contrato, LA PARTE RECEPTORA devolverá o destruirá toda la información confidencial y sus copias, certificando por escrito dicha destrucción." },
      { t: "h", x: "SÉPTIMA. Propiedad" },
      { t: "p", x: "La información confidencial seguirá siendo propiedad de LA PARTE REVELADORA. Este contrato no transfiere derecho, licencia ni titularidad alguna." },
      { t: "h", x: "OCTAVA. Pena convencional" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] En caso de divulgación no autorizada, la parte infractora pagará una pena convencional de ${{Monto de pena convencional}}, sin perjuicio de la reparación de daños adicionales." },
      { t: "h", x: "NOVENA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["LA PARTE REVELADORA", "{{Parte reveladora}}"], b: ["LA PARTE RECEPTORA", "{{Parte receptora}}"] },
    ],
    fns: [
      "La protección de la información confidencial se apoya en las disposiciones sobre secretos industriales de la Ley Federal de Protección a la Propiedad Industrial y en la libertad contractual del art. 1832 CCF.",
    ],
  },

  /* 05 ---------------------------------------------------------------- */
  {
    id: "05_mutuo",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Contrato de mutuo (préstamo de dinero)",
    categoria: "Instrumentos de crédito",
    base: "Arts. 2384 a 2397 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Contrato de mutuo que celebran {{Nombre del mutuante}}, “EL MUTUANTE”; y {{Nombre del mutuatario}}, “EL MUTUATARIO”.[[1]]" },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "EL MUTUANTE entrega en este acto a EL MUTUATARIO, quien recibe a su entera satisfacción, la cantidad de ${{Monto del préstamo}} ({{Monto con letra}} pesos M.N.) en calidad de préstamo." },
      { t: "h", x: "SEGUNDA. Plazo y forma de devolución" },
      { t: "p", x: "EL MUTUATARIO se obliga a devolver la suma prestada a más tardar el {{Fecha de devolución}}, mediante {{Forma de devolución}}." },
      { t: "h", x: "TERCERA. Intereses" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El préstamo devengará un interés ordinario del {{Interés ordinario}}% mensual sobre saldos insolutos. En mora, un interés moratorio del {{Interés moratorio}}% mensual.[[2]]" },
      { t: "h", x: "CUARTA. Lugar de pago" },
      { t: "p", x: "Los pagos se realizarán en {{Lugar o cuenta de pago}}, dejando EL MUTUANTE el comprobante correspondiente." },
      { t: "h", x: "QUINTA. Vencimiento anticipado" },
      { t: "p", x: "La falta de pago de {{Parcialidades para vencimiento}} parcialidades dará derecho a exigir el pago total del adeudo, sus intereses y accesorios." },
      { t: "h", x: "SEXTA. Garantía" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] En garantía, EL MUTUATARIO suscribe un pagaré por el monto total, y/o constituye {{Garantía}} sobre {{Bien en garantía}}." },
      { t: "h", x: "SÉPTIMA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL MUTUANTE", "{{Nombre del mutuante}}"], b: ["EL MUTUATARIO", "{{Nombre del mutuatario}}"] },
    ],
    fns: [
      "El mutuo es un contrato por el cual el mutuante transfiere la propiedad de dinero u otras cosas fungibles al mutuatario, quien se obliga a devolver otro tanto de la misma especie y calidad (art. 2384 CCF).",
      "El interés legal es del 9% anual (art. 2395 CCF); el convencional lo fijan las partes, pero un interés notoriamente desproporcionado puede reducirse por el juez (criterios sobre usura).",
    ],
  },

  /* 06 ---------------------------------------------------------------- */
  {
    id: "06_comodato",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Contrato de comodato (préstamo de bienes)",
    categoria: "Demanda general",
    base: "Arts. 2497 a 2515 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Contrato de comodato que celebran {{Nombre del comodante}}, “EL COMODANTE”; y {{Nombre del comodatario}}, “EL COMODATARIO”.[[1]]" },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "EL COMODANTE concede gratuitamente a EL COMODATARIO el uso temporal del siguiente bien: {{Descripción del bien}}. El comodato es esencialmente gratuito." },
      { t: "h", x: "SEGUNDA. Destino del bien" },
      { t: "p", x: "EL COMODATARIO destinará el bien exclusivamente para {{Uso del bien}} y no podrá darle un uso distinto ni concederlo a terceros." },
      { t: "h", x: "TERCERA. Plazo" },
      { t: "p", x: "El comodato durará {{Plazo del comodato}}, del {{Fecha de inicio}} al {{Fecha de término}}. EL COMODANTE podrá exigir la devolución antes del plazo si tuviere urgente necesidad del bien (art. 2512 CCF)." },
      { t: "h", x: "CUARTA. Conservación y gastos" },
      { t: "p", x: "EL COMODATARIO se obliga a conservar el bien con la mayor diligencia, cubriendo los gastos ordinarios de uso, sin derecho a reembolso (art. 2508 CCF)." },
      { t: "h", x: "QUINTA. Responsabilidad" },
      { t: "p", x: "EL COMODATARIO responde por la pérdida o deterioro del bien, aun por caso fortuito, cuando lo emplee para un uso distinto o por más tiempo del convenido (art. 2504 CCF)." },
      { t: "h", x: "SEXTA. Devolución" },
      { t: "p", x: "Al término del plazo, EL COMODATARIO restituirá el bien en el mismo estado en que lo recibió, salvo el desgaste por uso normal, en {{Lugar de devolución}}." },
      { t: "h", x: "SÉPTIMA. Prohibición de retención" },
      { t: "p", x: "EL COMODATARIO no podrá retener el bien bajo pretexto alguno, ni aun por los gastos o daños que hubiere erogado (art. 2509 CCF)." },
      { t: "h", x: "OCTAVA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL COMODANTE", "{{Nombre del comodante}}"], b: ["EL COMODATARIO", "{{Nombre del comodatario}}"] },
    ],
    fns: [
      "El comodato es un contrato por el cual uno concede gratuitamente el uso de una cosa no fungible y el otro se obliga a restituirla individualmente (art. 2497 CCF). Es esencialmente gratuito.",
    ],
  },

  /* 07 ---------------------------------------------------------------- */
  {
    id: "07_contrato_trabajo",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Contrato individual de trabajo",
    categoria: "Documentos laborales",
    base: "Ley Federal del Trabajo (arts. 24, 25 y relativos)",
    bloques: [
      { t: "p", x: "Contrato individual de trabajo por {{Tipo de contrato laboral}} que celebran {{Nombre/Razón social del patrón}}, “EL PATRÓN”; y {{Nombre del trabajador}}, “EL TRABAJADOR”.[[1]]" },
      { t: "h", x: "DECLARACIONES" },
      { t: "i", x: "I. EL PATRÓN: RFC {{RFC del patrón}}, registro patronal IMSS {{Registro patronal IMSS}}, domicilio {{Domicilio del patrón}}." },
      { t: "i", x: "II. EL TRABAJADOR: CURP {{CURP del trabajador}}, RFC {{RFC del trabajador}}, NSS {{NSS del trabajador}}, domicilio {{Domicilio del trabajador}}." },
      { t: "h", x: "PRIMERA. Puesto y funciones" },
      { t: "p", x: "EL TRABAJADOR prestará sus servicios como {{Puesto}}, desempeñando las siguientes funciones: {{Descripción de funciones}}." },
      { t: "h", x: "SEGUNDA. Lugar de trabajo" },
      { t: "p", x: "Los servicios se prestarán en {{Domicilio del centro de trabajo}}." },
      { t: "h", x: "TERCERA. Duración" },
      { t: "p", x: "El contrato es por {{Duración del contrato}}. [CLÁUSULA OPCIONAL] Se pacta un periodo a prueba de {{Días de periodo a prueba}} días (art. 39-A LFT)." },
      { t: "h", x: "CUARTA. Jornada" },
      { t: "p", x: "La jornada será {{Tipo de jornada}}, de {{Horario}}, con descanso para alimentos, y descanso semanal el {{Día de descanso}}.[[2]]" },
      { t: "h", x: "QUINTA. Salario" },
      { t: "p", x: "EL TRABAJADOR percibirá un salario de ${{Monto del salario}} ({{Salario con letra}}) {{Periodicidad del salario}}, pagadero en {{Lugar o cuenta de pago}}, nunca inferior al salario mínimo vigente." },
      { t: "h", x: "SEXTA. Prestaciones" },
      { t: "p", x: "EL TRABAJADOR gozará de las prestaciones de ley: aguinaldo (mín. 15 días), vacaciones (art. 76 LFT), prima vacacional 25%, IMSS, INFONAVIT y SAR. [CLÁUSULA OPCIONAL] Prestaciones adicionales: {{Prestaciones adicionales}}." },
      { t: "h", x: "SÉPTIMA. Obligaciones del trabajador" },
      { t: "p", x: "EL TRABAJADOR se obliga a desempeñar el trabajo con esmero, guardar confidencialidad, cuidar los bienes del patrón y observar el reglamento interior (art. 134 LFT)." },
      { t: "h", x: "OCTAVA. Relación laboral y disposiciones supletorias" },
      { t: "p", x: "En lo no previsto se estará a lo dispuesto por la Ley Federal del Trabajo. Los conflictos se someterán a los Tribunales Laborales competentes." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL PATRÓN", "{{Nombre/Razón social del patrón}}"], b: ["EL TRABAJADOR", "{{Nombre del trabajador}}"] },
    ],
    fns: [
      "El art. 25 de la Ley Federal del Trabajo enumera los requisitos mínimos del contrato individual. La falta de contrato escrito no priva al trabajador de sus derechos (art. 26); la carga de la prueba recae en el patrón.",
      "La jornada máxima es de 8 horas (diurna), 7 (nocturna) y 7.5 (mixta), art. 61 LFT. El salario no puede ser inferior al mínimo de la CONASAMI. Respete aguinaldo, vacaciones y prima vacacional.",
    ],
  },

  /* 08 ---------------------------------------------------------------- */
  {
    id: "08_renuncia_finiquito",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Carta de renuncia y recibo finiquito",
    categoria: "Documentos laborales",
    base: "Ley Federal del Trabajo (arts. 53, 87, 76, 80 y relativos)",
    bloques: [
      { t: "sub", x: "DOCUMENTO 1 — CARTA DE RENUNCIA" },
      { t: "p", x: "{{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "p", x: "{{Nombre/Razón social del patrón}} — Presente." },
      { t: "p", x: "Por medio de la presente, yo, {{Nombre del trabajador}}, manifiesto mi decisión libre, voluntaria y sin presión de dar por terminada la relación laboral, presentando mi renuncia irrevocable al puesto de {{Puesto}}, con efectos a partir del {{Fecha de efectos de la renuncia}}.[[1]]" },
      { t: "p", x: "Manifiesto que recibí el pago íntegro de mis salarios y prestaciones, y que no se me adeuda cantidad alguna por concepto distinto al finiquito de ley, agradeciendo la oportunidad brindada." },
      { t: "sign", a: ["EL TRABAJADOR", "{{Nombre del trabajador}}"], b: ["", ""] },
      { t: "br" },
      { t: "sub", x: "DOCUMENTO 2 — RECIBO FINIQUITO" },
      { t: "p", x: "En {{Ciudad de firma}}, a {{Fecha de firma}}, el suscrito {{Nombre del trabajador}} declaro haber recibido de {{Nombre/Razón social del patrón}} la cantidad de ${{Monto total del finiquito}} ({{Finiquito con letra}}) por concepto de finiquito, integrado por:" },
      { t: "i", x: "• Salarios devengados y no pagados: ${{Salarios devengados}}" },
      { t: "i", x: "• Aguinaldo proporcional (art. 87 LFT): ${{Aguinaldo proporcional}}" },
      { t: "i", x: "• Vacaciones proporcionales (art. 76 LFT): ${{Vacaciones proporcionales}}" },
      { t: "i", x: "• Prima vacacional 25% (art. 80 LFT): ${{Prima vacacional}}" },
      { t: "i", x: "• [CLÁUSULA OPCIONAL] Prima de antigüedad (art. 162 LFT, si aplica): ${{Prima de antigüedad}}" },
      { t: "p", x: "Con la cantidad recibida me doy por totalmente pagado y satisfecho de todas las prestaciones derivadas de la relación laboral, otorgando el más amplio finiquito que en derecho proceda, sin reservarme acción o derecho alguno." },
      { t: "sign", a: ["EL TRABAJADOR", "{{Nombre del trabajador}}"], b: ["", ""] },
    ],
    fns: [
      "La renuncia voluntaria no genera indemnización constitucional ni prima de antigüedad, salvo 15 o más años de servicio (art. 162 LFT). El finiquito comprende salarios, aguinaldo, vacaciones y prima vacacional proporcionales.",
    ],
  },

  /* 09 ---------------------------------------------------------------- */
  {
    id: "09_aviso_privacidad",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Aviso de privacidad integral",
    categoria: "Documentos digitales y cumplimiento",
    base: "Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP)",
    bloques: [
      { t: "p", x: "{{Nombre/Razón social del responsable}} (el “Responsable”), con domicilio en {{Domicilio del responsable}}, es responsable del tratamiento y protección de sus datos personales, conforme a la LFPDPPP, su Reglamento y demás normativa aplicable.[[1]]" },
      { t: "h", x: "1. Datos personales que se recaban" },
      { t: "p", x: "Para las finalidades señaladas, el Responsable podrá recabar los siguientes datos: {{Datos personales recabados}}." },
      { t: "note", x: "Datos sensibles: en caso de recabar datos sensibles (salud, biométricos, origen, creencias), se requiere consentimiento expreso y por escrito del titular." },
      { t: "h", x: "2. Finalidades del tratamiento" },
      { t: "p", x: "Finalidades primarias: {{Finalidades primarias}}. Finalidades secundarias (requieren que no manifieste su negativa): {{Finalidades secundarias}}." },
      { t: "h", x: "3. Transferencias de datos" },
      { t: "p", x: "Sus datos podrán transferirse a {{Destinatarios de transferencias}} para {{Finalidad de la transferencia}}. Salvo las excepciones del art. 37 LFPDPPP, requieren su consentimiento." },
      { t: "h", x: "4. Derechos ARCO" },
      { t: "p", x: "Usted tiene derecho a Acceder, Rectificar, Cancelar u Oponerse (derechos ARCO) y a revocar su consentimiento. Envíe su solicitud a {{Correo o domicilio para ARCO}}." },
      { t: "h", x: "5. Revocación del consentimiento" },
      { t: "p", x: "Puede revocar su consentimiento o solicitar la limitación del uso de sus datos mediante el procedimiento señalado." },
      { t: "h", x: "6. Uso de cookies" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El sitio web utiliza cookies y web beacons para {{Finalidad de cookies}}. Puede deshabilitarlas desde su navegador." },
      { t: "h", x: "7. Modificaciones al aviso" },
      { t: "p", x: "El presente aviso puede modificarse; los cambios se harán de su conocimiento a través de {{Medio de aviso de cambios}}." },
      { t: "p", x: "Fecha de última actualización: {{Fecha de actualización}}." },
    ],
    fns: [
      "El art. 16 de la LFPDPPP y los arts. 26 y 27 de su Reglamento establecen los elementos del aviso de privacidad. Los datos sensibles requieren consentimiento expreso y por escrito (art. 9).",
    ],
  },

  /* 10 ---------------------------------------------------------------- */
  {
    id: "10_terminos_condiciones",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Términos y condiciones de uso",
    categoria: "Documentos digitales y cumplimiento",
    base: "Código de Comercio, LFPC, LFPDPPP y Ley Federal del Derecho de Autor",
    bloques: [
      { t: "p", x: "Los presentes Términos y Condiciones regulan el acceso y uso del sitio web o aplicación {{Nombre o URL del sitio}}, operado por {{Titular del sitio}} (el “Titular”). Al usar la plataforma, el usuario acepta plenamente estos Términos.[[1]]" },
      { t: "h", x: "1. Objeto" },
      { t: "p", x: "Regular las condiciones de uso de {{Descripción del servicio}}." },
      { t: "h", x: "2. Capacidad del usuario" },
      { t: "p", x: "El Usuario declara ser mayor de edad y contar con capacidad legal para obligarse." },
      { t: "h", x: "3. Registro y cuenta" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El Usuario es responsable de la veracidad de sus datos y de la confidencialidad de sus credenciales de acceso." },
      { t: "h", x: "4. Uso permitido" },
      { t: "p", x: "El Usuario se obliga a usar la plataforma conforme a la ley, absteniéndose de: {{Conductas prohibidas}}." },
      { t: "h", x: "5. Propiedad intelectual" },
      { t: "p", x: "Todo el contenido (marcas, logotipos, textos, software, diseños) es propiedad del Titular o sus licenciantes, protegido por la LFDA y la legislación de propiedad industrial." },
      { t: "h", x: "6. Precios, pagos y devoluciones" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Los precios se expresan en pesos mexicanos. Las políticas de pago, envío y devolución se rigen por {{Política aplicable}} y por la LFPC." },
      { t: "h", x: "7. Protección de datos" },
      { t: "p", x: "El tratamiento de datos personales se rige por el Aviso de Privacidad disponible en {{URL del aviso de privacidad}}." },
      { t: "h", x: "8. Limitación de responsabilidad" },
      { t: "p", x: "El Titular no será responsable por daños derivados del uso o imposibilidad de uso de la plataforma, en la medida permitida por la ley." },
      { t: "h", x: "9. Modificaciones" },
      { t: "p", x: "El Titular podrá modificar estos Términos; los cambios entrarán en vigor al publicarse en {{URL del sitio}}." },
      { t: "h", x: "10. Ley aplicable y jurisdicción" },
      { t: "p", x: "Estos Términos se rigen por las leyes mexicanas. Para controversias, las partes se someten a los tribunales competentes de {{Ciudad y estado de jurisdicción}}, salvo los derechos irrenunciables del consumidor ante la PROFECO." },
      { t: "p", x: "Fecha de última actualización: {{Fecha de actualización}}." },
    ],
    fns: [
      "El comercio electrónico se rige, entre otros, por el Título Segundo del Código de Comercio (mensajes de datos), la LFPC (art. 76 bis) y la LFPDPPP. Ajuste según sea sitio informativo, e-commerce o app.",
    ],
  },

  /* 11 ---------------------------------------------------------------- */
  {
    id: "11_pagare",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Pagaré",
    categoria: "Instrumentos de crédito",
    base: "Arts. 170 a 174 de la Ley General de Títulos y Operaciones de Crédito (LGTOC)",
    bloques: [
      { t: "p", x: "Bueno por ${{Monto del pagaré}}   —   Lugar y fecha de suscripción: {{Ciudad de suscripción}}, a {{Fecha de suscripción}}." },
      { t: "p", x: "Debo(emos) y pagaré(mos) incondicionalmente por este PAGARÉ a la orden de {{Nombre del beneficiario}}, la cantidad de ${{Monto del pagaré}} ({{Monto con letra}} pesos M.N.), en la ciudad de {{Lugar de pago}}, el día {{Fecha de vencimiento}}.[[1]]" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Este pagaré causará intereses ordinarios del {{Interés ordinario}}% mensual desde su suscripción hasta su total liquidación; y en mora, intereses moratorios del {{Interés moratorio}}% mensual sobre el saldo insoluto." },
      { t: "p", x: "El (los) suscriptor(es) renuncia(n) a la presentación, protesto y aviso por falta de pago, y señala(n) como domicilio el ubicado en {{Domicilio del suscriptor}}." },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Comparece {{Nombre del aval}} otorgando su AVAL para garantizar el pago total, obligándose solidariamente con el suscriptor." },
      { t: "sign", a: ["EL SUSCRIPTOR (deudor)", "{{Nombre del suscriptor}}"], b: ["POR AVAL (en su caso)", "{{Nombre del aval}}"] },
      { t: "note", x: "Para su plena eficacia ejecutiva, el pagaré NO debe contener condiciones (la promesa de pago debe ser incondicional). Las cláusulas de intereses y aval son admisibles." },
    ],
    fns: [
      "El art. 170 LGTOC exige que el pagaré contenga: (I) la mención “pagaré” en el texto; (II) la promesa incondicional de pagar una suma determinada; (III) el nombre del beneficiario; (IV) época y lugar de pago; (V) fecha y lugar de suscripción; y (VI) la firma del suscriptor.",
    ],
  },

  /* 12 ---------------------------------------------------------------- */
  {
    id: "12_pacto_socios",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Pacto o convenio entre socios",
    categoria: "Corporativo y startups",
    base: "Ley General de Sociedades Mercantiles y art. 1832 CCF",
    bloques: [
      { t: "p", x: "Convenio entre socios que celebran las personas listadas en el Anexo A (los “Socios”) respecto de la sociedad {{Razón social de la sociedad}} (la “Sociedad”), al tenor de lo siguiente.[[1]]" },
      { t: "h", x: "PRIMERA. Objeto" },
      { t: "p", x: "Regular las relaciones entre los Socios, sus derechos y obligaciones, la gobernanza de la Sociedad y las condiciones de entrada y salida del capital, complementando los estatutos sociales." },
      { t: "h", x: "SEGUNDA. Capital y participaciones" },
      { t: "p", x: "El capital y su distribución se detallan en el Anexo A. Toda emisión, transmisión o dilución se sujetará a este convenio." },
      { t: "h", x: "TERCERA. Vesting de fundadores" },
      { t: "p", x: "Las participaciones de los fundadores se consolidarán (“vesting”) en un periodo de {{Periodo de vesting}} con un “cliff” de {{Periodo de cliff}}. En separación anticipada, la Sociedad o los demás Socios podrán readquirir las participaciones no consolidadas." },
      { t: "h", x: "CUARTA. Derecho de preferencia" },
      { t: "p", x: "Si un Socio desea transmitir sus participaciones, los demás tendrán derecho de preferencia para adquirirlas en proporción a su tenencia." },
      { t: "h", x: "QUINTA. Arrastre y acompañamiento (drag-along / tag-along)" },
      { t: "p", x: "Drag-along: si Socios que representen al menos el {{Porcentaje drag-along}}% aprueban la venta, podrán obligar a los demás a vender en las mismas condiciones. Tag-along: los minoritarios podrán sumarse a la venta del mayoritario en iguales condiciones." },
      { t: "h", x: "SEXTA. Anti-dilución" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] En rondas a valuación inferior a la previa, los Socios beneficiados tendrán un ajuste conforme al método {{Método anti-dilución}}." },
      { t: "h", x: "SÉPTIMA. Gobernanza y decisiones reservadas" },
      { t: "p", x: "Requerirán mayoría calificada las decisiones sobre: {{Decisiones reservadas}}." },
      { t: "h", x: "OCTAVA. No competencia y no captación" },
      { t: "p", x: "Durante su participación y por {{Plazo de no competencia}} posteriores a su salida, los Socios se obligan a no competir ni captar empleados o clientes en {{Territorio de no competencia}}." },
      { t: "h", x: "NOVENA. Confidencialidad" },
      { t: "p", x: "Los Socios mantendrán confidencialidad sobre la información de la Sociedad, obligación que subsistirá tras su salida." },
      { t: "h", x: "DÉCIMA. Resolución de controversias" },
      { t: "p", x: "Las controversias se resolverán mediante {{Mecanismo de controversias}}, conforme a la legislación mexicana." },
      { t: "p", x: "Firmado por los Socios en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["SOCIO 1", "{{Nombre del socio 1}}"], b: ["SOCIO 2", "{{Nombre del socio 2}}"] },
    ],
    fns: [
      "El pacto de socios es un contrato parasocial que complementa los estatutos y se apoya en la libertad contractual (art. 1832 CCF) y en la LGSM. Cláusulas como vesting, drag/tag-along y no competencia son válidas si no contravienen el orden público.",
    ],
  },

  /* 13 ---------------------------------------------------------------- */
  {
    id: "13_carta_poder",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Carta poder simple",
    categoria: "Poderes y representación",
    base: "Mandato para actos determinados (arts. 2546 y ss. CCF)",
    bloques: [
      { t: "p", x: "{{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "p", x: "{{Autoridad o empresa ante quien se presenta}} — Presente." },
      { t: "p", x: "Por medio de la presente, yo, {{Nombre del otorgante}}, con identificación {{Identificación del otorgante}} y domicilio en {{Domicilio del otorgante}}, otorgo poder tan amplio como en derecho corresponda a favor de {{Nombre del apoderado}}, con identificación {{Identificación del apoderado}}, para que en mi nombre realice el siguiente acto:[[1]]" },
      { t: "i", x: "{{Descripción del acto o gestión}}." },
      { t: "p", x: "El presente poder se otorga únicamente para el acto descrito y se extingue una vez realizado o en la fecha {{Fecha de vigencia}}." },
      { t: "sign", a: ["EL OTORGANTE", "{{Nombre del otorgante}}"], b: ["EL APODERADO (acepta)", "{{Nombre del apoderado}}"] },
      // sinFirmaAuto: los testigos son terceros. La firma que dibuja el otorgante
      // en el generador NO debe estamparse aquí; cada testigo firma de su puño.
      { t: "sign", sinFirmaAuto: true, a: ["TESTIGO 1", "{{Nombre del testigo 1}}"], b: ["TESTIGO 2", "{{Nombre del testigo 2}}"] },
    ],
    fns: [
      "La carta poder simple es válida para actos que no requieran escritura pública. Para trámites menores, gestiones administrativas o cobro de cheques, la carta poder con dos testigos es suficiente (art. 2555 CCF).",
    ],
  },

  /* 14 ---------------------------------------------------------------- */
  {
    id: "14_poder_general",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Poder general",
    categoria: "Poderes y representación",
    base: "Art. 2554 del Código Civil Federal (pleitos y cobranzas, administración y dominio)",
    bloques: [
      { t: "note", x: "PROYECTO / MINUTA para protocolización ante Notario Público. El poder general (particularmente actos de dominio) debe constar en escritura pública para su plena validez." },
      { t: "p", x: "En la ciudad de {{Ciudad de firma}}, comparece {{Nombre del poderdante}} (el “Poderdante”), y otorga PODER a favor de {{Nombre del apoderado}} (el “Apoderado”), en los siguientes términos.[[1]]" },
      { t: "h", x: "PRIMERA. Poder para pleitos y cobranzas" },
      { t: "p", x: "Se otorga poder general para PLEITOS Y COBRANZAS con todas las facultades generales y las especiales que requieran cláusula especial, para representar al Poderdante ante toda clase de autoridades judiciales, administrativas y laborales." },
      { t: "h", x: "SEGUNDA. Poder para actos de administración" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Se otorga poder general para ACTOS DE ADMINISTRACIÓN, para administrar bienes y negocios, celebrar contratos, contratar personal y manejar cuentas (art. 2554 CCF)." },
      { t: "h", x: "TERCERA. Poder para actos de dominio" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Se otorga poder general para ACTOS DE DOMINIO, con las facultades de dueño, incluyendo enajenar, gravar e hipotecar bienes del Poderdante." },
      { t: "h", x: "CUARTA. Facultades cambiarias" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Se otorgan facultades para suscribir, endosar y avalar títulos de crédito (art. 9 LGTOC)." },
      { t: "h", x: "QUINTA. Sustitución y revocación" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El Apoderado {{Facultad de sustitución}} sustituir o delegar el poder. El Poderdante se reserva el derecho de revocarlo en cualquier momento." },
      { t: "h", x: "SEXTA. Vigencia" },
      { t: "p", x: "El poder tendrá vigencia {{Vigencia del poder}}, salvo revocación." },
      { t: "p", x: "Firmado por el Poderdante para su protocolización ante Notario Público, en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL PODERDANTE", "{{Nombre del poderdante}}"], b: ["EL APODERADO (acepta)", "{{Nombre del apoderado}}"] },
    ],
    fns: [
      "El art. 2554 CCF define los tres tipos de poder general: pleitos y cobranzas, actos de administración y actos de dominio. El poder general, en especial el de dominio y el que incluye facultades cambiarias o de sustitución, debe otorgarse ante Notario Público en escritura pública.",
    ],
  },

  /* 15 ---------------------------------------------------------------- */
  {
    id: "15_declaracion_protesta",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Declaración bajo protesta de decir verdad",
    categoria: "Documentos complementarios",
    base: "Manifestación de hechos con efectos legales",
    bloques: [
      { t: "p", x: "{{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "p", x: "{{Autoridad o institución ante quien se presenta}} — Presente." },
      { t: "p", x: "Yo, {{Nombre del declarante}}, con identificación oficial {{Identificación del declarante}}, CURP {{CURP del declarante}}, y domicilio en {{Domicilio del declarante}}, bajo protesta de decir verdad y con conocimiento de las penas en que incurren quienes declaran con falsedad, DECLARO:[[1]]" },
      { t: "i", x: "1. {{Hecho o manifestación 1}}." },
      { t: "i", x: "2. {{Hecho o manifestación 2}}." },
      { t: "i", x: "3. {{Hecho o manifestación 3}}." },
      { t: "p", x: "Manifiesto que lo anterior es verídico y me hago responsable de su contenido, para {{Finalidad o trámite}}." },
      { t: "sign", a: ["EL DECLARANTE (Protesto lo necesario)", "{{Nombre del declarante}}"], b: ["", ""] },
    ],
    fns: [
      "La declaración bajo protesta es una manifestación unilateral con efectos legales. Declarar con falsedad ante autoridad distinta de la judicial puede constituir el delito del art. 247 Bis del Código Penal Federal y sus equivalentes locales.",
    ],
  },

  /* 16 ---------------------------------------------------------------- */
  {
    id: "16_reconocimiento_adeudo",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Convenio de reconocimiento de adeudo y pago",
    categoria: "Documentos complementarios",
    base: "Arts. 1792, 1793 y 2062 del Código Civil Federal",
    bloques: [
      { t: "p", x: "Convenio de reconocimiento de adeudo y forma de pago que celebran {{Nombre del acreedor}}, “EL ACREEDOR”; y {{Nombre del deudor}}, “EL DEUDOR”.[[1]]" },
      { t: "h", x: "DECLARACIONES" },
      { t: "i", x: "I. Declara EL DEUDOR que, por virtud de {{Origen del adeudo}}, adeuda a EL ACREEDOR la cantidad de ${{Monto del adeudo}} ({{Monto con letra}})." },
      { t: "i", x: "II. Declaran LAS PARTES su voluntad de documentar dicho adeudo y establecer un plan de pagos." },
      { t: "h", x: "PRIMERA. Reconocimiento de adeudo" },
      { t: "p", x: "EL DEUDOR reconoce expresamente adeudar a EL ACREEDOR la cantidad de ${{Monto del adeudo}}, cantidad líquida, cierta y exigible." },
      { t: "h", x: "SEGUNDA. Forma y calendario de pago" },
      /* "Fechas o periodicidad" pedía dos datos distintos en un solo hueco: cada
         quién contestaba una cosa ("mensual" o "los días 5") y la cláusula salía
         coja. Se separan para que siempre queden ambos. */
      { t: "p", x: "EL DEUDOR se obliga a pagar mediante {{Número de pagos}} pagos de ${{Monto de cada pago}} cada uno, con periodicidad {{Periodicidad de los pagos}}, los días {{Día de pago}}, en {{Lugar o cuenta de pago}}." },
      { t: "h", x: "TERCERA. Intereses" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El saldo generará intereses ordinarios del {{Interés ordinario}}% mensual; en mora, moratorios del {{Interés moratorio}}% mensual." },
      { t: "h", x: "CUARTA. Vencimiento anticipado" },
      { t: "p", x: "La falta de pago de {{Parcialidades para vencimiento}} parcialidades dará por vencido el plazo, siendo exigible la totalidad del saldo más accesorios." },
      { t: "h", x: "QUINTA. Garantía" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] En garantía, EL DEUDOR suscribe un pagaré por el saldo total y/o constituye {{Garantía}}." },
      { t: "h", x: "SEXTA. Jurisdicción" },
      { t: "p", x: "LAS PARTES se someten a las leyes y tribunales competentes de {{Ciudad y estado de jurisdicción}}, renunciando a cualquier otro fuero." },
      { t: "p", x: "Leído y enteradas LAS PARTES, firman por duplicado en {{Ciudad de firma}}, a {{Fecha de firma}}." },
      { t: "sign", a: ["EL ACREEDOR", "{{Nombre del acreedor}}"], b: ["EL DEUDOR", "{{Nombre del deudor}}"] },
    ],
    fns: [
      "El convenio de reconocimiento de adeudo documenta una deuda existente y su forma de pago. Para dotarlo de fuerza ejecutiva conviene acompañarlo de un pagaré. Se apoya en los arts. 1792, 1793 y 2062 (pago) del CCF.",
    ],
  },

  /* 17 ---------------------------------------------------------------- */
  {
    id: "17_recibo_renta",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Recibo de pago de renta",
    categoria: "Documentos complementarios",
    base: "Comprobante de pago de arrendamiento",
    bloques: [
      { t: "p", x: "Recibo No. {{Folio del recibo}}   —   Monto: ${{Monto de la renta}}" },
      { t: "p", x: "En {{Ciudad de firma}}, a {{Fecha de firma}}, el suscrito {{Nombre del arrendador}} (EL ARRENDADOR) declaro haber recibido de {{Nombre del arrendatario}} (EL ARRENDATARIO) la cantidad de:" },
      { t: "i", x: "${{Monto de la renta}} ({{Monto con letra}} pesos M.N.)" },
      { t: "p", x: "Por concepto de renta correspondiente al periodo del {{Fecha de inicio del periodo}} al {{Fecha de fin del periodo}}, del inmueble ubicado en {{Domicilio del inmueble}}." },
      { t: "p", x: "Forma de pago: {{Forma de pago}}. Referencia: {{Referencia de pago}}." },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Con este pago, el estado de cuenta del arrendatario se encuentra al corriente hasta la fecha señalada." },
      { t: "sign", a: ["EL ARRENDADOR", "{{Nombre del arrendador}}"], b: ["", ""] },
      { t: "note", x: "Este recibo no sustituye al Comprobante Fiscal Digital por Internet (CFDI) que, en su caso, deba expedir el arrendador conforme a la legislación fiscal." },
    ],
    fns: [],
  },

  /* 18 ---------------------------------------------------------------- */
  {
    id: "18_viaje_menores",
    que_es: "Documento legal que formaliza las obligaciones y derechos entre las partes respecto a este acto jurídico.",
    para_que_sirve: "Para dejar evidencia escrita de los acuerdos pactados, previniendo malentendidos y futuros litigios.",
    alcance_legal: "Genera obligaciones exigibles ante tribunales y protege los intereses de ambas partes conforme a la ley.",
    titulo: "Autorización de viaje para menores",
    categoria: "Documentos complementarios",
    base: "Formato SAM — Ley de Migración y lineamientos del INM",
    bloques: [
      { t: "p", x: "Los suscritos, en nuestro carácter de {{Carácter de quien autoriza}} de la persona menor de edad que más adelante se identifica, otorgamos la presente AUTORIZACIÓN DE VIAJE.[[1]]" },
      { t: "h", x: "1. Datos de quien(es) autoriza(n)" },
      { t: "i", x: "Nombre(s): {{Nombre de quien autoriza}}" },
      { t: "i", x: "Identificación: {{Identificación de quien autoriza}}   CURP: {{CURP de quien autoriza}}" },
      { t: "h", x: "2. Datos de la persona menor de edad" },
      { t: "i", x: "Nombre completo: {{Nombre del menor}}" },
      { t: "i", x: "Fecha de nacimiento: {{Fecha de nacimiento del menor}}   Nacionalidad: {{Nacionalidad del menor}}" },
      { t: "i", x: "CURP / pasaporte: {{CURP o pasaporte del menor}}" },
      { t: "h", x: "3. Datos de la persona acompañante" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] El menor viajará acompañado de {{Nombre del acompañante}}, con identificación {{Identificación del acompañante}}, parentesco {{Parentesco del acompañante}}." },
      { t: "h", x: "4. Datos del viaje" },
      { t: "i", x: "Destino: {{Destino del viaje}}" },
      { t: "i", x: "Fecha de salida: {{Fecha de salida}}   Fecha de regreso: {{Fecha de regreso}}" },
      { t: "i", x: "Medio de transporte / vuelo: {{Medio de transporte}}" },
      { t: "i", x: "Motivo del viaje: {{Motivo del viaje}}" },
      { t: "h", x: "5. Autorización" },
      { t: "p", x: "Manifestamos, bajo protesta de decir verdad, que ejercemos la patria potestad o tutela del menor y que autorizamos de manera libre y voluntaria su viaje en los términos descritos." },
      { t: "p", x: "Otorgada en {{Ciudad de firma}}, a {{Fecha de firma}}, para su ratificación ante Notario Público o autoridad competente." },
      { t: "sign", a: ["PADRE / TUTOR", "{{Nombre del padre o tutor}}"], b: ["MADRE / TUTORA", "{{Nombre de la madre o tutora}}"] },
    ],
    fns: [
      "Para la salida de menores mexicanos viajando solos o con terceros, el INM requiere el Formato SAM (Salida de Personas Menores de Edad) o autorización ante notario/fedatario o autoridad consular (Ley de Migración). Verifique el formato oficial y requisitos vigentes del INM antes de viajar.",
    ],
  },
  {
    id: "19_nota_pago_venta",
    que_es: "Es un comprobante privado que deja constancia de una venta o de un pago recibido, con el detalle de los bienes o servicios, el importe y los datos de quien vende y quien compra.",
    para_que_sirve: "Para documentar operaciones de mostrador, entregas de mercancía o pagos entre particulares cuando no se emite factura, y para tener un respaldo escrito de lo cobrado y lo entregado.",
    alcance_legal: "Acredita la operación entre las partes y sirve como prueba en caso de reclamación, pero no es un comprobante fiscal: no ampara deducciones ni acreditamiento de impuestos. Para efectos fiscales se requiere el CFDI correspondiente.",
    titulo: "Nota de pago / Nota de venta",
    categoria: "Documentos complementarios",
    base: "Comprobante simple de venta y pago (no fiscal)",
    bloques: [
      { t: "p", x: "NOTA DE VENTA / NOTA DE PAGO" },
      { t: "p", x: "Lugar y fecha de expedición: {{Ciudad de expedición}}, a {{Fecha de expedición}}." },
      { t: "h", x: "1. Datos del vendedor / emisor" },
      { t: "i", x: "Nombre o razón social: {{Nombre del vendedor}}" },
      { t: "i", x: "RFC: {{RFC del vendedor}}   Domicilio: {{Domicilio del vendedor}}" },
      { t: "i", x: "Teléfono / correo: {{Contacto del vendedor}}" },
      { t: "h", x: "2. Datos del cliente / comprador" },
      { t: "i", x: "Nombre o razón social: {{Nombre del cliente}}" },
      { t: "i", x: "RFC: {{RFC del cliente}}   Domicilio: {{Domicilio del cliente}}" },
      { t: "h", x: "3. Descripción del bien o servicio" },
      { t: "p", x: "Se hace constar la venta de los siguientes bienes y/o servicios:" },
      { t: "i", x: "Concepto: {{Bien o servicio}}" },
      { t: "i", x: "Descripción detallada: {{Descripción amplia del bien o servicio}}" },
      { t: "i", x: "Marca / modelo / especificaciones: {{Marca, modelo o especificaciones}}" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Número de serie / identificador: {{Número de serie o identificador}}" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Estado / condición: {{Estado o condición}}" },
      { t: "i", x: "Cantidad: {{Cantidad}}   Unidad de medida: {{Unidad de medida}}" },
      { t: "i", x: "Precio unitario: ${{Precio unitario}}   Importe: ${{Importe}}" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Conceptos adicionales: {{Conceptos adicionales}}   Importe: ${{Importe adicional}}" },
      { t: "h", x: "4. Totales" },
      { t: "i", x: "Subtotal: ${{Subtotal}}" },
      { t: "i", x: "[CLÁUSULA OPCIONAL] IVA (16%): ${{IVA}}" },
      { t: "i", x: "[CLÁUSULA OPCIONAL] Descuento: ${{Descuento}}" },
      { t: "i", x: "TOTAL: ${{Total}} ({{Total con letra}} pesos M.N.)" },
      { t: "h", x: "5. Comprobante de pago" },
      { t: "p", x: "El emisor declara haber recibido de {{Nombre del cliente}} la cantidad de ${{Monto pagado}} ({{Monto pagado con letra}} pesos M.N.), por concepto del pago total de la presente nota." },
      { t: "i", x: "Forma de pago: {{Forma de pago}}   Referencia: {{Referencia de pago}}" },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Saldo pendiente: ${{Saldo pendiente}}, que el cliente se obliga a cubrir a más tardar el {{Fecha de pago del saldo}}." },
      { t: "p", x: "[CLÁUSULA OPCIONAL] Garantía / observaciones: {{Garantía u observaciones}}" },
      { t: "sign", a: ["RECIBÍ (VENDEDOR)", "{{Nombre del vendedor}}"], b: ["CONFORME (CLIENTE)", "{{Nombre del cliente}}"] },
      { t: "note", x: "Esta nota es un comprobante simple de operación y NO tiene efectos fiscales. No sustituye al Comprobante Fiscal Digital por Internet (CFDI) que el vendedor deba expedir conforme a la legislación fiscal vigente. Consérvela como constancia de la operación.[[1]]" },
    ],
    fns: [
      "Las notas de venta o de remisión son documentos privados de uso comercial que acreditan la operación entre las partes, pero no son comprobantes fiscales. Para efectos de deducción o acreditamiento, el adquirente debe solicitar el CFDI correspondiente conforme al Código Fiscal de la Federación y sus disposiciones.",
    ],
  },
];

// Exponer global para el navegador
if (typeof window !== "undefined") window.CONTRATOS = CONTRATOS;
if (typeof module !== "undefined") module.exports = { CONTRATOS };
